### ISSUE TITLE
javafx Error

### ISSUE THREAD

**Issue by JoAllg** [DeOldSax/iliasDownloaderTool#49]
As mentioned in #15  it is not possible to start the downloader with JDK15 on Win10 64bit and possibley other versions too.
'''
D:\Desktop\IliasDownloaderTool-aluf-v1.2.2>java -jar ./Ilias-Downloader-Tool-aluf-v1.2.2.jar
Error: Could not find or load main class view.Dashboard
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
'''
It seems that problem can be bypassed with the "--add-modules javafx.web" flag as mentioned by vonHartz #15, however that probably works only on linux where a compiled version of javafx.web is in the shared libaries.

I guess the reason is, that JavaFX is not part of JDK/JRE since JDK11. I tried downloading the current version from https://gluonhq.com/products/javafx/ but were not able to use it.

**Comment by JoAllg** [comment]
Another Error I get with both KiT and aluf version:
'''
ubuntu@WinX1Y:/mnt/d/Desktop/IliasDownloaderTool-aluf-v1.2.2$ java -jar ./Ilias-Downloader-Tool-aluf-v1.2.2.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:873)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:142)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:140)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:278)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more
'''
This time I tried to use the precompiled versions in WSL after installing the dependencies as mentioned in the Readme.md

**Comment by DeOldSax** [comment]
are you sure you can start the java gui out of your wsl?
--> Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY

**Comment by JoAllg** [comment]
You have a very good point there! Gotta install such features first.

**Comment by DeOldSax** [comment]
As mentioned in the readme, the current JDK is JDK 8, preferably with javafx included.
To overcome this issue in the future and make it ready for JDK 11 and upcoming LTS versions, see #51
