### ISSUE TITLE
Invalid Username / Password (KIT)

### ISSUE THREAD

**Issue by hediet** [DeOldSax/iliasDownloaderTool#57]
If it works, it would be a nice and useful tool!

However, I could not login (using my `u...` account). It says "Falsches Passwort" ("Invalid Password"), even though the password is certainly correct.

If I retry, it crashes:
```
Exception in thread "Thread-6" java.lang.IllegalStateException: Connection pool shut down
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:185)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:251)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:175)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at plugin.KITIlias.executePost(KITIlias.java:106)
        at plugin.KITIlias.login(KITIlias.java:40)
        at control.IliasManager.login(IliasManager.java:31)
        at control.IliasStarter.login(IliasStarter.java:30)
        at control.LoginProvider$1.run(LoginProvider.java:53)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by DeOldSax** [comment]
against which version are getting this error?

**Comment by hediet** [comment]
> but not available at the website yet

Then thats the reason.

I can highly recommend setting up github actions to automize that ;)
They are free and super easy to configure.

**Comment by DeOldSax** [comment]
thx for the advice ;) As soon as i have free time available i will work on an automated deployment ;)

**Comment by hediet** [comment]
I'd suggest to keep this issue open until the bugfix is deployed, so others can find it.

**Comment by DeOldSax** [comment]
new version available at https://www.iliasdownloadertool.de/
